name: Example workflow

on: [push]

jobs:
  example:
    name: Minikube-Kubernetes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes-version:
          - 1.18.20
          - 1.19.16
          - 1.20.14
          - 1.21.11
          - 1.22.8
          - 1.23.5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube with Kubernetes ${{ matrix.kubernetes-version }}
        uses: manusa/actions-setup-minikube@v2.4.3
        with:
          minikube version: 'v1.24.0'
          kubernetes version: ${{ matrix.kubernetes-version }}
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster ${{ matrix.kubernetes-version }}
        run: kubectl get nodes